# Generated by Django 6.0.7 on 2026-07-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên vai trò")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã vai trò"
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Đường dẫn ảnh đại diện",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả ngắn"),
                ),
                ("system_prompt", models.TextField(verbose_name="Prompt hệ thống")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Kích hoạt"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vai trò Chatbot",
                "verbose_name_plural": "Danh sách Vai trò Chatbot",
                "db_table": "chatbot_roles",
            },
        ),
    ]
